version: '3.8'

services:
  postgres:
    build: .
    container_name: neximfel
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: touchMIDAS
        POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres18_data:/var/lib/postgresql
volumes:
  my_postgres_volume: